#ifndef ENUMS_H
#define ENUMS_H

enum Phase { INIT_PREPARSE, PREPARSE, INIT_PROGRAM, PROGRAM, INIT_JSON_PARSE, JSON_PARSE };

enum Type { K_BOOL, K_NUMBER, K_STRING, K_ANY, K_LIST, K_DICT, K_VOID };
enum ValueType { V_BOOL, V_INT, V_FLOAT, V_STRING, V_VOID };
enum Role { DEFAULT, PARAM, CALL_PARAM };

#endif
