#define __LANGUAGE_NAME__ "Chaos"
#define __LANGUAGE_VERSION__ "0.0.1-alpha"
#define __LANGUAGE_MOTTO__ "Turn chaos into magic!"
#define __BYE_BYE__ "You have chosen the order!"
#define __SHELL_INDICATOR__ "###"
