name: "[interpreter] Memory Sanitizer"

on: [push, pull_request]

jobs:
  main:
    name: sanitizer_memory
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (clang)
      run: |
        make clean
        make clang-dev-sanitizer-memory
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test-no-shell
