name: Linter Checks

on: [push, pull_request]

jobs:
  main:
    name: linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Lint with Cppcheck
      run: |
        sudo apt-get -y install cppcheck
        make lint
