name: Undefined Behavior Sanitizer

on: [push, pull_request]

jobs:
  main:
    name: sanitizer_undefined_behavior
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (clang)
      run: |
        make clean
        make clang-dev-sanitizer-undefined_behavior
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test
